var searchData=
[
  ['revision_20history',['Revision History',['../md___users_cascaval__barefoot__projects__p4_src_p4c_docs_doxygen_00_revision_history.html',1,'']]],
  ['repository',['Repository',['../md___users_cascaval__barefoot__projects__p4_src_p4c_docs__r_e_a_d_m_e.html',1,'']]],
  ['random_5fmodel',['Random_Model',['../struct_p4_v1_1_1_random___model.html',1,'P4V1']]],
  ['range',['Range',['../group__irdefs.html#class_i_r_1_1_range',1,'IR']]],
  ['rangeiter',['RangeIter',['../class_range_iter.html',1,'']]],
  ['referencemap',['ReferenceMap',['../class_p4_1_1_reference_map.html',1,'P4']]],
  ['register',['Register',['../group__irdefs.html#class_i_r_1_1_register',1,'IR']]],
  ['register_5fmodel',['Register_Model',['../struct_p4_v1_1_1_register___model.html',1,'P4V1']]],
  ['removeactionparameters',['RemoveActionParameters',['../class_p4_1_1_remove_action_parameters.html',1,'P4']]],
  ['removeallunuseddeclarations',['RemoveAllUnusedDeclarations',['../class_p4_1_1_remove_all_unused_declarations.html',1,'P4']]],
  ['removecomplexexpressions',['RemoveComplexExpressions',['../class_b_m_v2_1_1_remove_complex_expressions.html',1,'BMV2']]],
  ['removeexits',['RemoveExits',['../class_p4_1_1_remove_exits.html',1,'P4']]],
  ['removeleftslices',['RemoveLeftSlices',['../class_p4_1_1_remove_left_slices.html',1,'P4']]],
  ['removenestedstructs',['RemoveNestedStructs',['../class_p4_1_1_remove_nested_structs.html',1,'P4']]],
  ['removeparsercontrolflow',['RemoveParserControlFlow',['../class_p4_1_1_remove_parser_control_flow.html',1,'P4']]],
  ['removereturns',['RemoveReturns',['../class_p4_1_1_remove_returns.html',1,'P4']]],
  ['removeselectbooleans',['RemoveSelectBooleans',['../class_p4_1_1_remove_select_booleans.html',1,'P4']]],
  ['removeunuseddeclarations',['RemoveUnusedDeclarations',['../class_p4_1_1_remove_unused_declarations.html',1,'P4']]],
  ['removeuselesscasts',['RemoveUselessCasts',['../class_p4_1_1_remove_useless_casts.html',1,'P4']]],
  ['renamemap',['RenameMap',['../class_p4_1_1_rename_map.html',1,'P4']]],
  ['renamesymbols',['RenameSymbols',['../class_p4_1_1_rename_symbols.html',1,'P4']]],
  ['replacementmap',['ReplacementMap',['../class_p4_1_1_replacement_map.html',1,'P4']]],
  ['resetheaders',['ResetHeaders',['../class_p4_1_1_reset_headers.html',1,'P4']]],
  ['resolutioncontext',['ResolutionContext',['../class_p4_1_1_resolution_context.html',1,'P4']]],
  ['resolve',['resolve',['../struct_p4_1_1_extern_instance.html#ac0ceabef5929cf1e206731d0d086d4cf',1,'P4::ExternInstance::resolve(const IR::Expression *expr, ReferenceMap *refMap, TypeMap *typeMap, const boost::optional&lt; cstring &gt; &amp;defaultName=boost::none)'],['../struct_p4_1_1_extern_instance.html#a381b6b1140a2e997670e9436c3d3f7ea',1,'P4::ExternInstance::resolve(const IR::PathExpression *path, ReferenceMap *refMap, TypeMap *typeMap)']]],
  ['resolvereferences',['ResolveReferences',['../class_p4_1_1_resolve_references.html',1,'P4']]],
  ['returnstatement',['ReturnStatement',['../group__irdefs.html#class_i_r_1_1_return_statement',1,'IR']]],
  ['rewriteallparsers',['RewriteAllParsers',['../class_p4_1_1_rewrite_all_parsers.html',1,'P4']]],
  ['rewritetablekeys',['RewriteTableKeys',['../class_p4_1_1_do_local_copy_propagation_1_1_rewrite_table_keys.html',1,'P4::DoLocalCopyPropagation']]],
  ['root',['root',['../struct_p4_1_1_control_plane_a_p_i_1_1_header_field_path.html#a72ce36ec7865569572a6a68144b78d1c',1,'P4::ControlPlaneAPI::HeaderFieldPath']]]
];
